# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-10 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20171205_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='rank',
            field=models.IntegerField(verbose_name='rank'),
        ),
    ]
